/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_STUBCLIENT_H_
#define JSONRPC_CPP_STUB_STUBCLIENT_H_

#include <jsonrpccpp/client.h>

class StubClient : public jsonrpc::Client
{
    public:
        StubClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        void getServoStatus() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p = Json::nullValue;
            this->CallNotification("getServoStatus",p);
        }
        void set_servo_status(const std::string& status) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["status"] = status;
            this->CallNotification("set_servo_status",p);
        }
};

#endif //JSONRPC_CPP_STUB_STUBCLIENT_H_
